application: rsvp-app
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: main.app

- url: /signup
  script: main.app
  secure: always

- url: /login
  script: main.app
  secure: always

- url: /forgot
  script: main.app
  secure: always

- url: /css
  static_dir: css

- url: /fonts/codropsicons
  static_dir: fonts/codropsicons

- url: /js
  static_dir: js

- url: /img
  static_dir: img
